# Generated by Django 2.2.4 on 2020-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link5', '0002_saved_models_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('stock', models.IntegerField()),
                ('manufacturing_cost', models.IntegerField()),
                ('selling_cost', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='saved_models',
        ),
    ]
