# Generated by Django 2.2.4 on 2020-11-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link5', '0003_auto_20201126_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='DT',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
